CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
id INTEGER(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(100) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT false,
date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);

